env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"

task:
  name: SSH CI
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'TTTT55'
  timeout_in: 4h
  condition:
    repo: x86_64_build
    branch: main
  persistent_worker:
    labels:
      name: AX61-1
    isolation:
      environment:
        image: ubuntu:latest
        cpu: 24
        memory: 120G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
  clone_script:
    - git clone https://github.com/TTTT55/x86_64_build.git
  
  setup_script:
    - curl -L https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
    - fisher install tmate-io/tmate
  
  script:
    - tmate -S /tmp/tmate.sock new-session -d
    - tmate -S /tmp/tmate.sock wait tmate-ready
    - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > ssh_url.txt
    - tmate -S /tmp/tmate.sock display -p '#{tmate_web}' >> ssh_url.txt
    - cat ssh_url.txt
