env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    bot_api: "bot1822006486:AAGX5JWqloJdIin7XbhjtVSsFWb06B3Uk1w"

task:
  name: Build
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'TTTT55'
  depends_on: Test
  timeout_in: 4h
  persistent_worker:
    labels:
      name: AX61-1
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 24
        memory: 120G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
  show_script: cat $CIRRUS_WORKING_DIR/build_rom.sh
  test_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/test.sh | bash
  sync_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/sync.sh | bash
  tsync_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/tsync.sh | bash
  build_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/build.sh | bash
  ccache_stats_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/ccache_stats.sh | bash
  upload_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/upload.sh | bash
  remove_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/remove.sh | bash

task:
  name: Post Build
  skip: $CIRRUS_BRANCH == 'main'
  only_if: $CIRRUS_REPO_OWNER == 'TTTT55'
  skip_notifications: true
  depends_on: Build
  timeout_in: 2m
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 2
        memory: 4G
  test_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/test.sh | bash
  post_build_script: curl -s https://raw.githubusercontent.com/TTTT55/x86_64_build/main/ci/post_build.sh | bash
