task:
  name: SSH CI
  timeout_in: 4h
  condition:
    repo: x86_64_build
    branch: main
  persistent_worker: {}
  environment:
    image: ubuntu:latest
    cpu: 24
    memory: 120G
  clone_script:
    - git clone https://github.com/TTTT55/x86_64_build.git
  
  setup_script:
    - curl -L https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
    - fisher install tmate-io/tmate
  
  script:
    - tmate -S /tmp/tmate.sock new-session -d
    - tmate -S /tmp/tmate.sock wait tmate-ready
    - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > ssh_url.txt
    - tmate -S /tmp/tmate.sock display -p '#{tmate_web}' >> ssh_url.txt
    - cat ssh_url.txt
#
